def build_app
  gym(
    scheme: 'TFGMLive'
  )
end

lane :new_version do
  increment_version_number
end

lane :beta do
  increment_build_number
  build_app
  upload_to_testflight(
    username: "imboredkidsapp@gmail.com"
  )
end

lane :appstore do
  capture_screenshots
  build_app
  upload_to_app_store
  increment_version_number
end
