def build_app
  gym(
    scheme: 'TFGMLive'
  )
end

def upload_to_testflight
  username "imboredkidsapp@gmail.com"
end

lane :beta do
  increment_build_number
  build_app
  upload_to_testflight
end

lane :appstore do
  capture_screenshots
  build_app
  upload_to_app_store
end
