def build_app
  gym(
    scheme: 'TFGMLive'
  )
end

lane :new_version do
  increment_version_number
  increment_build_number(
    build_number: "1"
  )
end

lane :reset_build_number do
  increment_build_number(
    build_number: "1"
  )
end

lane :beta do
  increment_build_number
  build_app
  upload_to_testflight(
    username: "imboredkidsapp@gmail.com",
    skip_waiting_for_build_processing: true
  )
end

lane :appstore do
  capture_screenshots(
    clear_previous_screenshots: true,
    erase_simulator: true,
    reinstall_app: true
  )
  build_app
  upload_to_app_store
  increment_version_number
end
